### PR TITLE
wrap cmd in exec

### PR DESCRIPTION
**Pull request by Nesze**

### CODE REVIEW

**Comment by Zapadlo** [comment]
Could we instead get ETCD_PEERS from the ENV and instead use `CMD ["/vulcan-config-builder"]`? That would be nice...

**Comment by catalin-ilea** [comment]
Do we still need this?

**Comment by Zapadlo** [comment]
It would be ideal to move the only param to an ENV var and make `CMD ["/vcb"]` the entrypoint, if its not much effort

**Comment by Nesze** [comment]
Already fixed.

**Pull request closed without merging**
