### PR TITLE
Configured failover predicates for frontends.

### PR DESCRIPTION
**Pull request by catalin-ilea**

### CODE REVIEW

**Comment by catalin-ilea** [comment]
I initially considered making "(IsNetworkError() || ResponseCode() == 503 || ResponseCode() == 500) && Attempts() <= 1" configurable per service by adding this in the sidekicks. But do we need this to be different for services?

**Comment by catalin-ilea** [comment]
Any reason why we shouldn't retry for non idempotent methods(PUT, POST) with the way our platform works?

**Comment by khatton-ft** [comment]
@catalin-ilea that would violate the Principle of Least Astonishment.

**Comment by Zapadlo** [comment]
@catalin-ilea 
1. Can you make the config the default with optional override in the sidekick?
2. I don't see why not.

@khatton-ft I don't think that applies here.

**Comment by khatton-ft** [comment]
@Zapadlo The whole point of PoLA is that it applies everywhere, surely.

**Comment by catalin-ilea** [comment]
@khatton-ft I agree, it's def not best practice but I think it will make our lives easier in the publishing pipelines. What do others think? @sjwells @nwrigh @tamas-molnar

**Comment by tamas-molnar** [comment]
It's fine by me, it might reduce the number of failed publishes. The fact that we retry by default should be documented somewhere though.

**Comment by Zapadlo** [comment]
+1

**Comment by yolandeleungFT** [comment]
It's fine by me also. I think we should be consistent until we find something that really has to behave differently.

**Pull request merged**
